tta/bookings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.view_booking, name='view-booking'),
    path('search/', views.search, name='search'),
    path('book/', views.book, name='book'),
    path('cancel/', views.cancel, name='cancel'),
]

tta/tta/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from bookings import views as booking_views
from users import views as user_views

urlpatterns = [
    path('', user_views.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('bookings/', include('bookings.urls')),
    path('wallet/', booking_views.wallet, name='wallet')
]

tta/bookings/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone

from users import views as user_views
from users.models import Passenger


class Wallet(models.Model):
    passenger = models.OneToOneField(Passenger, on_delete=models.CASCADE)
    balance = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0)]
    )

    class Meta:
        verbose_name = 'Wallet'

    def __str__(self):
        return f'{self.passenger.username} Wallet'


class Train(models.Model):
    train_no = models.IntegerField(
        verbose_name='Train Number',
    )

    train_name = models.CharField(
        verbose_name='Train Name',
        max_length=30,
    )

    source = models.CharField(
        verbose_name='Source',
        max_length=30,
    )

    destination = models.CharField(
        verbose_name='Destination',
        max_length=30,
    )

    seats_remaining = models.IntegerField(
        verbose_name='# of seats remaining',
        validators=[MinValueValidator(0)],
    )

    departure_time = models.TimeField(
        verbose_name='Departure time',
    )

    travel_time = models.DurationField(
        verbose_name='Travel time'
    )

    fare = models.IntegerField(
        verbose_name='Fare',
        validators=[MinValueValidator(100)],
    )

    class Meta:
        verbose_name = 'Train'

    def __str__(self):
        return self.train_name


class Booking(models.Model):
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    train = models.ForeignKey(Train, on_delete=models.CASCADE)

    date = models.DateField(
        verbose_name='Travel Date',
        default=timezone.now,
    )

    pnr_no = models.CharField(
        verbose_name='PNR Number',
        max_length=10,
    )

    seats_booked = models.IntegerField(
        verbose_name='# of seats booked',
        validators=[MinValueValidator(1)],
    )

    class Meta:
        verbose_name = 'Booking'

    def __str__(self):
        return f'{self.passenger.username} - #{self.pnr_no}'

tta/bookings/forms.py
from datetime import date, timedelta

from django import forms
from django.core.exceptions import ValidationError

from .models import Booking, Train

increment_choices = (
    ('100', '100'),
    ('500', '500'),
    ('1000', '1000'),
    ('2000', '2000'),
)


class AddMoneyForm(forms.Form):
    amount = forms.ChoiceField(
        choices=increment_choices,
        widget=forms.RadioSelect,
    )


class SearchForm(forms.Form):
    source = forms.CharField(
        label='Source',
        max_length=30,
    )
    destination = forms.CharField(
        label='Destination',
        max_length=30,
    )
    doj = forms.DateField(
        label='Date',
    )
    seats = forms.IntegerField(
        label='Seats',
        min_value=1,
    )

    def clean_doj(self):
        cd = self.cleaned_data
        booking_date = cd.get('doj')
        if booking_date < date.today() + timedelta(days=1):
            raise ValidationError('This date has already passed!')

        return booking_date

tta/bookings/views.py
from random import randint
from time import sleep
from urllib.parse import urlencode

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse

from .forms import AddMoneyForm, SearchForm
from .models import Booking, Train


@login_required
def view_booking(request):
    bookings = Booking.objects.filter(passenger=request.user.passenger)
    return render(request, 'bookings/view.html', {'bookings': bookings})


@login_required
def wallet(request):
    if request.method == 'POST':
        addmoney_form = AddMoneyForm(request.POST)
        if addmoney_form.is_valid():
            increment = int(addmoney_form.cleaned_data.get('amount'))
            wallet_obj = request.user.passenger.wallet
            wallet_obj.balance += increment
            wallet_obj.save()
            messages.success(request, f'Added money successfully')
            # sleep is to make the redirect more natural feeling
            sleep(0.5)
            return redirect('wallet')
    else:
        addmoney_form = AddMoneyForm()
    return render(request, 'bookings/wallet.html', {'form': addmoney_form})


@login_required
def search(request):
    if request.method == 'POST':
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            src = search_form.cleaned_data.get('source')
            dst = search_form.cleaned_data.get('destination')
            raw_doj = search_form.cleaned_data.get('doj')
            doj = raw_doj.strftime("%b %d, %Y")
            seats = search_form.cleaned_data.get('seats')
            wallet_balance = request.user.passenger.wallet.balance
            trains = Train.objects.filter(
                source=src,
                destination=dst,
                seats_remaining__gte=seats,
                fare__lte=wallet_balance/int(seats),
            )
            context = {
                'trains': trains,
                'source': src,
                'destination': dst,
                'doj': doj,
                'seats': seats,
                'url_query': urlencode({'seats': seats, 'doj': raw_doj}),
            }
            if trains:
                return render(request, 'bookings/search_results.html', context)
            else:
                messages.error(request, f'No trains found from {src} to {dst}')
                return redirect('search')
    else:
        search_form = SearchForm()
    return render(request, 'bookings/search.html', {'form': search_form})


@login_required
def book(request):
    if request.method == 'GET':
        # if GET dict is empty
        if not request.GET:
            return redirect('profile')
        passenger = request.user.passenger
        train = Train.objects.filter(id=int(request.GET.get('id')))[0]
        doj = request.GET.get('doj')
        seats = request.GET.get('seats')
        pnr_no = str(randint(10**9, 10**10-1))
        new_booking = Booking(
                passenger=passenger,
                train=train,
                date=doj,
                pnr_no=pnr_no,
                seats_booked=seats,
        )
        new_booking.save()
        messages.success(request, f'Tickets booked successfully!')
    return redirect('profile')


@login_required
def cancel(request):
    if request.method == 'GET':
        # if GET dict is empty
        if not request.GET:
            return redirect('profile')
        booking = Booking.objects.filter(id=int(request.GET.get('id')))[0]
        booking.delete()
        messages.success(request, f'Ticket cancelled')
    return redirect('profile')

tta/bookings/templates/bookings/booking.html
{% extends "bookings/booking_base.html" %}
{% load booking_date_format %}
{% block table %}
<p></p>
{% endblock table %}

tta/bookings/templates/bookings/booking_base.html
{% extends "users/base.html" %}
{% block content %}
<div class="content-section">
    <legend class="border-bottom mb-4">Book Ticket</legend>
    <table class="table table-bordered" align="center">
        <tbody>
            <tr>
                <td><b>Source</b></td>
                <td align="center">{{ source|upper }}</td>
            </tr>
            <tr>
                <td><b>Destination</b></td>
                <td align="center">{{ destination|upper }}</td>
            </tr>
            <tr>
                <td><b>Date of Journey</b></td>
                <td align="center">{{ doj }}</td>
            </tr>
            <tr>
                <td><b>Seats required</b></td>
                <td align="center">{{ seats }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% block table %}{% endblock table %}
{% endblock content %}

tta/bookings/templates/bookings/search.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block extra_js %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(document).ready(function () {
        $("#id_doj").datepicker({ minDate: 1 });
    });
</script>
{% endblock extra_js %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Search Train</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Search</button>
            </div>
        </form>
    </div>
{% endblock content %}

tta/bookings/templates/bookings/search_results.html
{% extends "bookings/booking_base.html" %}
{% load booking_date_format %}
{% block table %}
<table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Train Name</th>
        <th scope="col">Departure Time</th>
        <th scope="col">Travel Time</th>
        <th scope="col">Seats available</th>
        <th scope="col">Fare</th>
        </tr>
    </thead>
    <tbody>
    {% for train in trains %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td align="center">{{ train.train_name }}</td>
            <td align="center">{{ train.departure_time|time:"H:i" }}</td>
            <td align="center">{{ train.travel_time|duration }}</td>
            <td align="center">{{ train.seats_remaining }}</td>
            <td align="center">{{ train.fare }}</td>
            <td align="center">
                <a class="btn btn-outline-success" href="{% url 'book' %}?id={{ train.id }}&{{ url_query }}">
                    Book
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock table %}

tta/bookings/templates/bookings/view.html
{% extends "users/base.html" %}
{% block content %}
    <div class="content-section">
        <legend class="border-bottom mb-4">View Booked Tickets</legend>
    {% if bookings|length == 0 %}
    <p>You have no bookings yet.</p>
    <small class="text-muted">
        New booking?<a class="ml-2" href="{% url 'search' %}">Click here</a>
    </small>
    {% else %}
    <p>You have {{ bookings|length }} bookings.</p>
    </div>
    <table class="table">
        <thead class="table">
            <tr>
            <th scope="col">#</th>
            <th scope="col">PNR #</th>
            <th scope="col">Train Name</th>
            <th scope="col">Source</th>
            <th scope="col">Destination</th>
            <th scope="col">DOJ</th>
            <th scope="col">Number of Tickets</th>
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td align="center">{{ booking.pnr_no }}</td>
                <td align="center">{{ booking.train.train_name }}</td>
                <td align="center">{{ booking.train.source|upper }}</td>
                <td align="center">{{ booking.train.destination|upper }}</td>
                <td align="center">{{ booking.date }}</td>
                <td align="center">{{ booking.seats_booked }}</td>
                <td align="center"><a class="btn btn-outline-danger" href="{% url 'cancel' %}?id={{ booking.id }}">Cancel Ticket</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock content %}

tta/bookings/templates/bookings/wallet.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Wallet</h2>
    <p class="my-5">Welcome to your wallet! You may add money or check your current balance. While booking tickets, the fare will automatically get deducted from your wallet.</p>
    <button type="button" class="btn btn-outline-info mx-1 my-4" data-toggle="modal" data-target="#checkBalanceModal">
        Check Balance
    </button>
    <button type="button" class="btn btn-outline-info mx-1 my-4" data-toggle="modal" data-target="#addMoneyModal">
        Add Money to Wallet
    </button>

    <!-- Check Balance -->
    <div class="modal fade" id="checkBalanceModal" tabindex="-1" role="dialog" aria-labelledby="checkBalanceModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="checkBalanceModalLabel">Wallet Balance</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p align="center">Current Balance: ₹{{ user.passenger.wallet.balance }}</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-info" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
    </div>

    <div class="modal fade" id="addMoneyModal" tabindex="-1" role="dialog" aria-labelledby="addMoneyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="checkBalanceModalLabel">Add Money</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
        </div>
        <div class="modal-footer form-group">
            <button class="btn btn-outline-info" type="submit">Add</button>
        </div>
        </form>
        </div>
    </div>
    </div>
{% endblock content %}